# Generated by Django 2.0b1 on 2017-11-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='VerifyCode',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
